.TH "D:\VisualStudio2015Projects\FuzzyCMeans\FuzzyCMeans\doc/html/search Directory Reference" 3 "Tue Jul 13 2021" "Version v1.0" "Fuzzy C-means in native C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:\VisualStudio2015Projects\FuzzyCMeans\FuzzyCMeans\doc/html/search Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsearch\&.js\fP"
.br
.ti -1c
.RI "file \fBsearchdata\&.js\fP"
.br
.in -1c
