.TH "DataTypes.h" 3 "Tue Jul 13 2021" "Version v1.0" "Fuzzy C-means in native C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataTypes.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <climits>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <numeric>\fP
.br
\fC#include <complex>\fP
.br
\fC#include <functional>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< float > \fBFloatVector\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBFloatVector\fP > \fBFloatVector2D\fP"
.br
.ti -1c
.RI "typedef std::vector< double > \fBDoubleVector\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBDoubleVector\fP > \fBDoubleVector2D\fP"
.br
.ti -1c
.RI "typedef std::vector< int > \fBIntVector\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBIntVector\fP > \fBIntVector2D\fP"
.br
.ti -1c
.RI "typedef std::vector< std::string > \fBStringVector\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBStringVector\fP > \fBStringVector2D\fP"
.br
.ti -1c
.RI "typedef std::pair< int, int > \fBIntIntPair\fP"
.br
.ti -1c
.RI "typedef std::pair< int, float > \fBIntFloatPair\fP"
.br
.ti -1c
.RI "typedef std::map< int, int > \fBIntIntMap\fP"
.br
.ti -1c
.RI "typedef std::map< int, \fBIntVector\fP > \fBIntIntVectorMap\fP"
.br
.ti -1c
.RI "typedef std::map< int, \fBFloatVector\fP > \fBIntFloatVectorMap\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::vector<double> \fBDoubleVector\fP"

.PP
Definition at line 25 of file DataTypes\&.h\&.
.SS "typedef std::vector<\fBDoubleVector\fP> \fBDoubleVector2D\fP"

.PP
Definition at line 26 of file DataTypes\&.h\&.
.SS "typedef std::vector<float> \fBFloatVector\fP"

.PP
Definition at line 23 of file DataTypes\&.h\&.
.SS "typedef std::vector<\fBFloatVector\fP> \fBFloatVector2D\fP"

.PP
Definition at line 24 of file DataTypes\&.h\&.
.SS "typedef std::pair<int,float> \fBIntFloatPair\fP"

.PP
Definition at line 32 of file DataTypes\&.h\&.
.SS "typedef std::map<int,\fBFloatVector\fP> \fBIntFloatVectorMap\fP"

.PP
Definition at line 35 of file DataTypes\&.h\&.
.SS "typedef std::map<int,int> \fBIntIntMap\fP"

.PP
Definition at line 33 of file DataTypes\&.h\&.
.SS "typedef std::pair<int,int> \fBIntIntPair\fP"

.PP
Definition at line 31 of file DataTypes\&.h\&.
.SS "typedef std::map<int,\fBIntVector\fP> \fBIntIntVectorMap\fP"

.PP
Definition at line 34 of file DataTypes\&.h\&.
.SS "typedef std::vector<int> \fBIntVector\fP"

.PP
Definition at line 27 of file DataTypes\&.h\&.
.SS "typedef std::vector<\fBIntVector\fP> \fBIntVector2D\fP"

.PP
Definition at line 28 of file DataTypes\&.h\&.
.SS "typedef std::vector<std::string> \fBStringVector\fP"

.PP
Definition at line 29 of file DataTypes\&.h\&.
.SS "typedef std::vector<\fBStringVector\fP> \fBStringVector2D\fP"

.PP
Definition at line 30 of file DataTypes\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fuzzy C-means in native C++ from the source code\&.
