.TH "GenericFunc.h" 3 "Tue Jul 13 2021" "Version v1.0" "Fuzzy C-means in native C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericFunc.h
.SH SYNOPSIS
.br
.PP
\fC#include 'DataTypes\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgf\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBgf::getExecutablePath\fP ()"
.br
.ti -1c
.RI "std::string \fBgf::getExecutablePathAndMatchItWithFilename\fP (std::string filename)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fuzzy C-means in native C++ from the source code\&.
