.TH "GenericFunc.cpp" 3 "Tue Jul 13 2021" "Version v1.0" "Fuzzy C-means in native C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericFunc.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'GenericFunc\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Fuzzy C-means in native C++ from the source code\&.
