.TH "gf" 3 "Tue Jul 13 2021" "Version v1.0" "Fuzzy C-means in native C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gf
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBgetExecutablePath\fP ()"
.br
.ti -1c
.RI "std::string \fBgetExecutablePathAndMatchItWithFilename\fP (std::string filename)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string gf::getExecutablePath ()"
Returns the absolute path of the executable's directory\&. 
.PP
\fBReturns:\fP
.RS 4
the absolute path of the executable's directory\&. 
.RE
.PP

.PP
Definition at line 3 of file GenericFunc\&.cpp\&.
.SS "std::string gf::getExecutablePathAndMatchItWithFilename (std::string filename)"
Returns the absolute path a file located in the executable's directory\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfileName\fP the name of the file (e\&.g\&., file\&.txt) 
.RE
.PP
\fBReturns:\fP
.RS 4
the absolute path of the file 
.RE
.PP

.PP
Definition at line 10 of file GenericFunc\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fuzzy C-means in native C++ from the source code\&.
