.TH "main.cpp" 3 "Tue Jul 13 2021" "Version v1.0" "Fuzzy C-means in native C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'FuzzyCMeans\&.h'\fP
.br
\fC#include 'GenericFunc\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 7 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fuzzy C-means in native C++ from the source code\&.
