.TH "MathFunc.h" 3 "Tue Jul 13 2021" "Version v1.0" "Fuzzy C-means in native C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MathFunc.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmfnc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > std::vector< T > \fBmfnc::multiplyVectorByConstant\fP (const std::vector< T > &v, const T &c)"
.br
.ti -1c
.RI "template<typename T > std::vector< T > \fBmfnc::addVectors\fP (const std::vector< T > &v_1, const std::vector< T > &v_2)"
.br
.ti -1c
.RI "template<typename T > void \fBmfnc::addToVector\fP (std::vector< T > &v, const std::vector< T > &other_v)"
.br
.ti -1c
.RI "template<typename T > double \fBmfnc::computeEuclideanDistance\fP (const std::vector< T > &v_1, const std::vector< T > &v_2)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fuzzy C-means in native C++ from the source code\&.
