.TH "md__r_e_a_d_m_e" 3 "Tue Jul 13 2021" "Version v1.0" "Fuzzy C-means in native C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- README 
This repo contains an implementation of the fuzzy C-means clustering machine learning algorithm:
.PP
https://en.wikipedia.org/wiki/Fuzzy_clustering
.PP
as a native C++ application\&.
.PP
The documentation of the project is in the /doc directory\&. 
