.TH "mfnc" 3 "Tue Jul 13 2021" "Version v1.0" "Fuzzy C-means in native C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mfnc
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > std::vector< T > \fBmultiplyVectorByConstant\fP (const std::vector< T > &v, const T &c)"
.br
.ti -1c
.RI "template<typename T > std::vector< T > \fBaddVectors\fP (const std::vector< T > &v_1, const std::vector< T > &v_2)"
.br
.ti -1c
.RI "template<typename T > void \fBaddToVector\fP (std::vector< T > &v, const std::vector< T > &other_v)"
.br
.ti -1c
.RI "template<typename T > double \fBcomputeEuclideanDistance\fP (const std::vector< T > &v_1, const std::vector< T > &v_2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > void mfnc::addToVector (std::vector< T > & v, const std::vector< T > & other_v)"

.PP
Definition at line 36 of file MathFunc\&.h\&.
.SS "template<typename T > std::vector<T> mfnc::addVectors (const std::vector< T > & v_1, const std::vector< T > & v_2)"

.PP
Definition at line 24 of file MathFunc\&.h\&.
.SS "template<typename T > double mfnc::computeEuclideanDistance (const std::vector< T > & v_1, const std::vector< T > & v_2)"

.PP
Definition at line 45 of file MathFunc\&.h\&.
.SS "template<typename T > std::vector<T> mfnc::multiplyVectorByConstant (const std::vector< T > & v, const T & c)"

.PP
Definition at line 13 of file MathFunc\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fuzzy C-means in native C++ from the source code\&.
