.TH "Point.cpp" 3 "Tue Jul 13 2021" "Version v1.0" "Fuzzy C-means in native C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Point\&.h'\fP
.br
\fC#include 'MathFunc\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <numeric>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Fuzzy C-means in native C++ from the source code\&.
