.TH "PropertiesParser.cpp" 3 "Tue Jul 13 2021" "Version v1.0" "Fuzzy C-means in native C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PropertiesParser.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'PropertiesParser\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Fuzzy C-means in native C++ from the source code\&.
